name: Manual CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install nbconvert

      - name: Convert Notebook and Train Model
        run: |
          source venv/bin/activate
          jupyter nbconvert --to script Final_Loss_Function_and_Optimizers.ipynb
          python Final_Loss_Function_and_Optimizers.py

      - name: Deploy Model
        run: |
          source venv/bin/activate
          nohup python app.py &
